### ISSUE TITLE
Selected field contains HTML

### ISSUE THREAD

**Issue by devExcale** [AustinHasten/AnkiKanjiTable#1]
Hi!

I use a plugin to colour my cards based on the pitch accent of the kanji, which puts a <span> tag on the kanji to colour it. The first character of the field is then showed on the grid, but it is "<" (because of the span tag) so the grid doesn't actually show the kanji.

The bug can be reproduced by creating a card and wrapping any kanji/character in a html tag, the grid should show a "<" only.
It could be fixed by parsing the HTML and getting the innermost content (i.e. the kanji, hopefully), would it be possible to do it?

Thanks

The following image is what I see; I'm colouring the cards as I get to them, so most of them don't have tags yet and show as intended.

![image](https://github.com/AustinHasten/AnkiKanjiTable/assets/49204811/d084cd15-873b-480c-8df0-51106a7cf6d4)

**Comment by AustinHasten** [comment]
Check out the new version and let me know if this addresses this point: https://www.reddit.com/r/LearnJapanese/comments/18zg63f/comment/kgkzp0h/?utm_source=share&utm_medium=web2x&context=3

**Comment by devExcale** [comment]
Yes, the new update solved the issue, thanks.

(Plugin version 2024-01-06)
