### ISSUE TITLE
Field contains multiple kanji

### ISSUE THREAD

**Issue by devExcale** [AustinHasten/AnkiKanjiTable#2]
Hi again!

I'm using a deck that contains words that are composed of multiple kanji (in addition to cards with the base meanings of the single kanji). This makes it so that only the first kanji is shown, and (false) duplicates are shown in the grid (see image at the bottom).

I was thinking that perhaps it'd be possible to fix this by adding a button to filter cards with multiple characters, so that only the single-kanji cards are shown.

Thanks

![image](https://github.com/AustinHasten/AnkiKanjiTable/assets/49204811/f981546b-bd3b-4c69-897a-b9aba8925e6a)

**Comment by AustinHasten** [comment]
Check out the new version and let me know if this addresses your point: https://www.reddit.com/r/LearnJapanese/comments/18zg63f/comment/kgkzp0h/?utm_source=share&utm_medium=web2x&context=3

**Comment by devExcale** [comment]
Yes, the new update solved the issue, thanks.

(Plugin version 2024-01-06)
